### ISSUE TITLE
(Possible) Issue caused by Error instantiation with null causedBy argument

### ISSUE THREAD

**Issue by danmpopa** [altmann/FluentResults#104]
Hi,

When instantiating using overloaded [constructor](https://github.com/altmann/FluentResults/blob/41587720fc70498855d97dce33d7ce718d6c1c14/src/FluentResults/Reasons/Error.cs#L43) or deriving **Error** class and calling base constructor with null *causedBy* we could get a *System.NullReferenceException* when  browsing *Errors* list items and trying to access item properties, e.g. check [here](https://github.com/altmann/FluentResults/blob/master/src/FluentResults/Factories/ResultHelper.cs#L34) if **error** is null.

Exception evidence:
![image](https://user-images.githubusercontent.com/65804146/139581705-a87751fd-9dd1-45d1-bb0b-e98a7e6d5ebf.png)

Replacing [this](https://github.com/altmann/FluentResults/blob/master/src/FluentResults/Reasons/Error.cs#L43) with following sentence could help:
`
            if (causedBy != null)
            {
                Reasons.Add(causedBy);
            }
`

Hope it helps,
M

**Comment by altmann** [comment]
Thank you for your feedback. 

I would prefer to throw an ArgumentNullException if causedBy is null so that the developer know that this is not a valid usage. If I implement it with the if expression (your suggestion) then it fails silently and its much harder to debug. 

What do you think?

**Comment by danmpopa** [comment]
Depending of your intention when you designed the class; if _causedBy_ is not optional your use-case applies, but for a better perspective on my suggestion, please see the Error class refactorization (overloaded ctor).
[Error.zip](https://github.com/altmann/FluentResults/files/7549496/Error.zip)

**Comment by altmann** [comment]
I don't like these default parameter initialization much. If you mix it with some other constructors then its unclear for the consumer how to use it correctly. 

I will implement the nullargument exception in the next days and discuss it with some people. Its an interesting topic. Multiple constructors vs one constructor with default parameter init.

**Comment by danmpopa** [comment]
Fair enough, you call the shots.

From my perspective, as a package "customer" (consumer) I had this use-case: create an user account with following prerequisites: (simplified version) there is no other user with same name registered, therefore I have this method in a repository class which verifies the user name registration:

```
public async Task<Result<User>> GetUserByUserNameAsync(string userName, CancellationToken cancelationToken = default)
{
    if (string.IsNullOrWhiteSpace(userName))
    {
        return Result.Fail<User>(new ArgumentNullOrDefaultError(nameof(userName)));
    }

    // Check if user already fetched from database, else will be retrieved:
    var filter = Builders<User>.Filter.Eq(nameof(User.UserName), userName);

    var user = await GetUserByFilter(filter, cancelationToken);

    if (user == null)
    {
        return Result.Fail<User>(new UserNotFoundByUserNameError(userName));
    }

    return Result.Ok(user);
}
```

In this case if it fails then I'm safe and the account can be created.

As you can see there is no `Error causedBy` involved in `UserNotFoundByUserNameError` ctor nor I do what to control code execution using exception.

My conclusions: 
- I use the constructor with `causedBy` if there is an exception caught/involved in the context;
- I more than OK with _overloaded constructor_, genuine OOP approach;
- As time as solves the issue I'm more than happy.

My opinion: if there is a non-optional parameter in a method (or ctor), without default value in definition, then a valid value should be supplied as an argument, meaning a validation should be done (sometimes `Empty` represents a valid value, e.g.: `EventArgs.Empty`).

Have these as pure subjective opinions, a matter of taste even if there are some principles behind the scenes.

**Comment by altmann** [comment]
New version is out => https://www.nuget.org/packages/FluentResults/3.1.0

Thank you again for your feedback. I solved this problem now with a second constructor and a required causedBy parameter. I also added some more null checks in the error class.
