### ISSUE TITLE
Prmomote Error ctor to protected virtual

### ISSUE THREAD

**Issue by danmpopa** [altmann/FluentResults#107]
Hi & Merry Christmas to everyone! :)

Is there a chance on next releases to have ~~private~~ protected ~~and virtual~~ _Error_ constructor for an increased flexibility? Also _Message_ property could have `init` .

One of the reasons would be to derive and easily instantiate the _Error_ delaying setting up the Message especially when the _Message_ is formed using `ctor` args; e.g.:

```
public class ArgumentNullOrDefaultError : Error
{
    public ArgumentNullOrDefaultError() : base("Argument must not be null or having default value!")
    { }

    public ArgumentNullOrDefaultError(string argumentName) : base(argumentName) // This will not be necessary anymore
    {
        if (string.IsNullOrWhiteSpace(argumentName))
        {
            throw new ArgumentException($"Argument '{nameof(argumentName)}' must not be null or having default value!");
        }

        Message = $"Argument '{argumentName}' must not be null nor having default value!"; // Here is the message initialisation
    }
}
```

**Comment by altmann** [comment]
Hi

I think this is a good idea. I'am now on vacation. You can make the changes and create a PR. I will review it next year and create a new release of FluentResults.

**Comment by danmpopa** [comment]
Hi,

For some reason I couldn't push a new branch - 403, but see attached file ([Error.zip](https://github.com/altmann/FluentResults/files/7813772/Error.zip)).

_Observations:_ I couldn't use `init` for _Message_ because of platform limitations (c# 7.3), needs 9.0 or above.

Also consider following:
- moving _ReasonFormat_ utility class into a separate file and make it static (see [this recommendation](https://rules.sonarsource.com/csharp/RSPEC-1118));
- use [Google Style Guide](https://google.github.io/styleguide/csharp-style.html) for C#;
- should _empty_ Message be a valid one? (also I've seen some tests validating this scenario, e.g.:: FluentResults.Test -> ErrorTests -> CreateError_EmptyError)

I hope these changes make sense.

**Comment by altmann** [comment]
I released a new version with protected parameterless constructors for the classes Success and Error. https://www.nuget.org/packages/FluentResults/3.2.0

Thanks for your feedback!

PS
=> ReasonFormat utility class improvement will come later
=> Empty Message is valid? Yes its valid. This behavior is there since v1. Therefore I don't want to change it in a minor version because maybe some consumers need this behavior. Maybe it will be changed in the next major version.
