### ISSUE TITLE
Integration into WebApi

### ISSUE THREAD

**Issue by Sonnenspeer** [altmann/FluentResults#111]
Hello,

I like the concept of having an action result instead of exceptions to handle logical errors.

Usually with exceptions I would implement custom domain exceptions which will be thrown in the application layer inside a mediator. Those would be catched through a middleware pipeline and be represented as the same status code. So in my controller I would return the wanted "successfull" status code (e.g. Ok, CreatedAtAction, NoContent) but on exceptional states the middleware would handle it.

Now with results there is some additional overhead and any error can't be catched as simple as that.

Are there some business examples which shows how the result pattern can be integrated into the WebApi easily with restful actions? So that every related status code to the restful api could be returned?

**Comment by altmann** [comment]
Hi, thanks for your question. I know what you mean. One team of my employer had the same challenge. Our solution was the following
- The mediator return a Result or Result<T> object
- There is one central logic which handles all results and converts it to a http response
  - business/domain results (Result, Result<T>) => Http Bad Request Status Code
  - SecurityException => Http Unauthorized
  - EntityNotFoundException => Http Not Found
  - all other exceptions => Http Internal Server Error
  - ....
- This central logic is not spread across a web api pipeline and something else. This central logic is called in the controller. So a controller method calls the mediator handler, take the result and convert it via the central logic to the http response
- This central logic can be a ControllerBase extension method for example. You can also integrate it in the mediator pipeline. 

I hope this will help you.
