### ISSUE TITLE
Any reason for requiring failure objects to derive from `Error`?

### ISSUE THREAD

**Issue by johnknoop** [altmann/FluentResults#112]
Hi!

If I want to return a failure using `Result.Fail<MySuccessType>(new MyErrorType("hello"))` then you already know it's a failure (since I called `Fail`) so you don't need the object type in order to tell a successful result from a failure. So is there a good reason or could you remove this constraint?

Cheers

**Comment by altmann** [comment]
Sorry, I dont understand your question. Can you please explain it in another way.

**Comment by johnknoop** [comment]
I'm wondering what the reason is for the constraint that all failure objects (that you pass to `Result.Fail` must derive from your `Error` type.

**Comment by altmann** [comment]
I most of the cases you want to pass error messages. Therefore there is a method to pass only strings. See https://github.com/altmann/FluentResults#creating-a-result

This library supports a hierarchical way of designing errors, details see https://github.com/altmann/FluentResults#root-cause-of-the-error Therefore you need a base class to save the required properties on the error object. See class for more details: 
https://github.com/altmann/FluentResults/blob/master/src/FluentResults/Reasons/IError.cs

Whats the problem with this constraint?

**Comment by johnknoop** [comment]
It just seems a bit arbitrary. It's not a huge trouble for me to let my error objects derive from `Error`, I just think it would be cleaner if they didn't have to, since it's not really needed for anything.

**Comment by altmann** [comment]
You can also derive from ```IError``` if you want.
