### ISSUE TITLE
Feature : HasException<>

### ISSUE THREAD

**Issue by pilouk** [altmann/FluentResults#113]
You guys are doing a really good job on this library !
I manage to get my exception type but it would be really nice to retrieve an exception more easily

Here an example to retrieve an exception that was added in the _causedby_
` bool expired = result.Errors.Any(e => e.Reasons.OfType<ExceptionalError>().Any(r => r.Exception.GetType() == typeof(SecurityTokenExpiredException)));`

A new method could help reduce the complexity without us having to create a static extension method ->
` bool expired = result.HasException<SecurityTokenExpiredException>();`

**Comment by altmann** [comment]
Thanks for your feedback!

I understand your feature and I think its a good idea. If you want to support me it would be great if you create a pull request with this feature. If not it will take some time.

**Comment by pilouk** [comment]
> Thanks for your feedback!
> 
> I understand your feature and I think its a good idea. If you want to support me it would be great if you create a pull request with this feature. If not it will take some time.

done -> https://github.com/altmann/FluentResults/pull/114

**Comment by altmann** [comment]
Thanks for your contribution! If you are still motivated then you can also extend the readme dicunentation. If not then I will do it. I will release the new version in the next days.

**Comment by pilouk** [comment]
> Thanks for your contribution! If you are still motivated then you can also extend the readme dicunentation. If not then I will do it. I will release the new version in the next days.

Just committed the documentation

**Comment by altmann** [comment]
Thank you! I merged it and will release a new version today.
