### ISSUE TITLE
[Proposal] Include error information in exception thrown on attempt to obtain value of failed result.

### ISSUE THREAD

**Issue by FlaviusHouk** [altmann/FluentResults#115]
## Motivation
In case result is failed somewhere and it wasn't properly checked, attempt to get a Value of a Result<T> will cause throwing an exception. It currently has a static message "Result is in status failed. Value is not set.". It allows to trace the source of error (in stack trace), but it might not be clear what caused it. Of course one might just refactor code to check IsFailed and throw or return another result with required information, I think it would be useful to print errors in this exception as well. It will help to identify problem in such situations. 

## Example
```
var result = Result.Fail<int>("Some error");
int value = result.Value; //throws InvalidOperationException("Result is in status failed. Value is not set. Having: Some error");
```

## API Changes
There is not public API changes. Getter and setter for Result.Value should be adjusted to format more informative message like this
```
if(IsFailed)
{
     string errorString = ReasonFormat.ReasonsToString(Errors);
     throw new InvalidOperationException("Result is in status failed. Value is not set. Having: {errorString}");
}
```

**Comment by altmann** [comment]
Thank you for the feedback. Very good idea. If you are motivated you can create a pull request with this improvement and I will have a look at it.

**Comment by altmann** [comment]
Thank you. It's merged. New version will come soon.
