### ISSUE TITLE
Timestamp in reasons

### ISSUE THREAD

**Issue by dyha89** [altmann/FluentResults#116]
Hi
In some usecases I have noticed that it would be nice to have a timestamp in Reasons/Errors/Successes.
Are you considering to add such property to IReason?

Other option could be some custom action in setup, like:
Result.Setup(cfg => 
{
  cfg.ReasonCustomAction(reason => reason.WithMetadata("Timestamp",DateTime.Now));
}

Such custom action would be called in all IReason classes constructors.

What do you think?

Great library btw :)

**Comment by altmann** [comment]
Thanks for the feedback. 

I think you can implement this behavior with the already existing extension points. Please create a child class from IError/Error and ISuccess/Success and add the timestamp as Metadata in the constructor. 

```
public class TimeStampError : Error
{
    public TimeStampError()
    {
         this.WithMetadata("Timestamp", DateTime.Now);
    }
}
```

Same for Success. I hope this is helpful. Maybe a good solution is to have the possibility to register custom factory methods for IError and ISuccess. I will have a look at it and let the issue opened.

**Comment by altmann** [comment]
I released a new version of FluentResults some minutes ago - [FluentResults 3.4.0](https://www.nuget.org/packages/FluentResults/3.4.0)

In the new version we can configure the creation of IError/ISuccess and IExceptionalError which are created within the library. With these new extension points you can implement your needed timestamp handling in a more elegant way. 
Details see [Set global factories for ISuccess/IError/IExceptionalError](https://github.com/altmann/FluentResults#set-global-factories-for-isuccessierroriexceptionalerror)

**Comment by dyha89** [comment]
Hi,
Sweet :) That's exactly what I need :)
And in fact factory looks more elegant than action :)
Thanks a lot :)
Closing the issue.
