### ISSUE TITLE
Missing editor documentation.

### ISSUE THREAD

**Issue by KevinValmo** [altmann/FluentResults#120]
Hello and nice work with this library!

I am using it, as a nuget, by following the readme.md file wich is fine and detailed but I noticed when I was writing some code in the editor (in my case VS 2022) that the editor documentation regarding methods, classes and field is missing.

Here below two simple examples:

![image](https://user-images.githubusercontent.com/55260200/163975198-ec0be0bb-8d7f-400c-9d1f-090f47ab8e91.png)
![image](https://user-images.githubusercontent.com/55260200/163975958-2adf2ce3-d4f9-4c1b-ac0c-16452fa60ee7.png)

Can it be provided as nuget **xml documentation**?
It would be very helpful if it will be fully integrated in the editor. Isn't it?

Thank a lot!

**Comment by altmann** [comment]
Thanks for the feedback. Yes you are right, the most of the public api documentation is missing. Why? I have no good reason. I will have a look at this topic but be aware that it will take probably some weeks to release a new version with the editor documentation.

**Comment by KevinValmo** [comment]
Thank you for the reply.
Don't worry about release weeks since there is already a very good entry point for the documentation with the README file and the Wiki.

**Comment by altmann** [comment]
Thank you so much for your pr. I merged it already in the master. A new release will come hopefully in the next days
