### ISSUE TITLE
Possibility to add multiple errors in Result.Fail<Model>()

### ISSUE THREAD

**Issue by GimmeDaKitty** [altmann/FluentResults#122]
I have just discovered this library and I find it really useful, so thank you for making it available :)

For our use case, a result might contain multiple error (reasons).
I was just wondering whether it is possible to add multiple errors in the Resul.Fail method, like so:

var errors = new List<string>("error1", "error2");
var result = Result.Fail<Model>(errors);

I don't think the interface supports it. Would you be open to a PR to extend this functionality, if it matches the current architecture/design vision of the library?

**Comment by altmann** [comment]
Hi, yes you are right. The current api doesn't support it. I like the idea and it fits to the current design. If you are motivated you can create a pr with this functionality. 4 new methods have to be added and some new tests. 2 methods for list of strings and list of IError and two methods for Result.Fail TValue and Result.Fail

Thanks for your feedback

**Comment by GimmeDaKitty** [comment]
Created PR #125

**Comment by GimmeDaKitty** [comment]
Hi, did you have the chance to have a look at the PR?

**Comment by altmann** [comment]
Hi, I am currently at vacation and I have to fix the release pipeline to publish New releases to nuget. So think I will have time for that all in june. Sorry for that.

**Comment by altmann** [comment]
Thank you so much for your pr. I made the review and added some comments. If you want then you can work in the comments. If not then please let me know then I will do the rest in the next weeks.

**Comment by altmann** [comment]
A new version is released https://www.nuget.org/packages/FluentResults/3.6.0

Thanks again for your time!

**Comment by GimmeDaKitty** [comment]
Sorry I did not react on time, glad to see the new release!
