### ISSUE TITLE
[question] HasException bug or feature.

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [altmann/FluentResults#126]
Hello 

Is this a bug or a feature ? I expect `HasException()` to return true in this case, but it returns false.
The code below can be used to reproduce.

```csharp
var result = Result.Fail(new ExceptionalError(new ArgumentException("test")));
Assert.True(result.HasException<ArgumentException>());
```

**Comment by pilouk** [comment]
Exceptions are validated from the CausedBy() method. You might want to used HasError() in your case

**Comment by altmann** [comment]
Thank you for your question. @pilouk was right - exceptions are validated against all added exceptions with the CausedBy() method. This means that all errors in the top level error list (Result.Errors) are ignored and only the errors in the Reasons list of the errors in the top level error list (Result.Errors[0].Reasons) are searched. 

@pilouk introduced this feature in FluentResults. For me it would maked sense that also the top level errors are searched. @ievgenii-shepeliuk also expected this behavior. What do you think? Why do you implement it in that way?

**Comment by pilouk** [comment]
> Thank you for your question. @pilouk was right - exceptions are validated against all added exceptions with the CausedBy() method. This means that all errors in the top level error list (Result.Errors) are ignored and only the errors in the Reasons list of the errors in the top level error list (Result.Errors[0].Reasons) are searched.
> 
> @pilouk introduced this feature in FluentResults. For me it would maked sense that also the top level errors are searched. @ievgenii-shepeliuk also expected this behavior. What do you think? Why do you implement it in that way?

@altmann I might be wrong but because they are actually different types? Your "Error" class definition must implement an interface "IError" which is not compatible with the Exception type. Therefore I thought it would be more logical to have a different function for a different type. In the same way, I'm not sure it would make any sense that HasError would be able to search for an Exception since Error ≠ Exception. Maybe a person would like to search only for an exception instead of an Error?

**Comment by pilouk** [comment]
@altmann I didn't anticipate that someone could add an Exception through an Error without using the CausedBy function.

**Comment by pilouk** [comment]
@altmann created a pull request for this : #130

**Comment by altmann** [comment]
A new version is released https://www.nuget.org/packages/FluentResults/3.6.0

Thanks again for your time!
