### ISSUE TITLE
[quesion] Implicit operator to convert TValue to Result<TValue>

### ISSUE THREAD

**Issue by rkosmirak** [altmann/FluentResults#129]
Hello, 

Just wondering, did you consider adding an implicit operator for converting `TValue` to `Result<TValue>`?

Currently, when you have a method that returns `Result<TValue>` you always need to return `Result.Ok(new TValue())`, but, it can be changed to just returning `new TValue()` instead.

**Comment by altmann** [comment]
Hi, thanks for your question. I think this would be a good enhancement for the consumers of the library. It would be great if you can create a pr for this feature. 

Maybe this issue is interesting for you - it is the other way around #84

**Comment by altmann** [comment]
Thanks for your time. The new release: https://www.nuget.org/packages/FluentResults/3.7.0

**Comment by rkosmirak** [comment]
Thanks
