### ISSUE TITLE
[question] How about adding functional magic?

### ISSUE THREAD

**Issue by EdwOK** [altmann/FluentResults#132]
Hello @altmann,

First of all I want to big thanks for this beautiful library.

Next, I'd like to consider the simple case when the library is used in a regular flow like this:
```csharp
var customerResult = GetCustomerById(customerId);
if (customerResult.IsFailed) 
    return customerResult.ToResult();

var addressResult = UpdateCustomerAddress(customerResult.Value, address);
if (addressResult.IsFailed)
    return addressResult.ToResult();
    
// continue working with addressResult.Value
```
Looking at this chain of `if-return` statements (in imperative style) makes me want to somehow reduce the number of lines in the code. In order to achieve is using the techniques of `functional programming` like [here](https://github.com/vkhorikov/CSharpFunctionalExtensions#compose-multiple-operations-in-a-single-chain) to be able to build a chain of methods:
```csharp
return GetCustomerById(customerId)
    .OnSuccess(customer => UpdateCustomerAddress(customer, address));
```

Have you thought about that?

**Comment by altmann** [comment]
Hi, thanks for your feedback. 

Someone created already an issue for that. See #108 If you need it you can implement it in your own project (its only extension methods). Gain experience with that style and I think then we can talk again. 

It is much effort to bring this functional style into this library and its much more effort to maintain it the next years. See the issues in https://github.com/vkhorikov/CSharpFunctionalExtensions/issues. Most of the issues are about the functional style methods.
