### ISSUE TITLE
add Deconstruct Operators to Result and ResultBase #137

### ISSUE THREAD

**Issue by Azaferany** [altmann/FluentResults#138]
Hello,

Currently, when you have a method that returns Result you always need to check isSuccess with result.IsSuccess its all ok although
add some Deconstruction method can make it more simple

var (isSuccess, isFailure, value) = Result.Ok(100);
var (isSuccess, value) = Result.Ok(100);
var (isSuccess, value, errors) = Result.Success(100);
 
 [#137](https://github.com/altmann/FluentResults/pull/137) has whats in my mind

**Comment by altmann** [comment]
PR: #137

**Comment by altmann** [comment]
Pushed v3.8 to nuget. Thanks for your pr
