### ISSUE TITLE
Lazy error evaluation of Result.OkIf and Result.FailIf

### ISSUE THREAD

**Issue by mtyski** [altmann/FluentResults#141]
As far as I am aware, the factory methods `OkIf` and `FailIf` need the `Error` instances to be provided at the moment they are called.

This may pop up in scenarios, where a reported `Error` instance requires access to the data which might not exist:

```CSharp
var list = Enumerable.Range(1, 9).ToList();

// will throw an InvalidOperationException
var result = Result.FailIf(
    list.Any(IsDivisibleByTen),
    $"Item {list.First(IsDivisibleByTen)} should not be on the list!");

// snip

static bool IsDivisibleByTen(int i) => i % 10 == 0;
```

The proposed feature would be to implement following method overloads:

- `Result.OkIf(bool condition, Func<string>)`
- `Result.OkIf(bool condition, Func<Error>)`
- `Result.FailIf(bool, Func<string>)` 
- `Result.FailIf(bool, Func<Error>)`

which would enable lazy evaluation of the errors; modifying the previous snippet:

```CSharp
var list = Enumerable.Range(1, 9).ToList();

// will not throw, as the Func<string> should not be called
var result = Result.FailIf(
    list.Any(IsDivisibleByTen),
    () => $"Item {list.First(IsDivisibleByTen)} should not be on the list!");

// snip

static bool IsDivisibleByTen(int i) => i % 10 == 0;
```

The workarounds to this are:
- use safe methods, which do not throw exceptions in such cases or
- use ternary / if statements.

**Comment by altmann** [comment]
Looks good. Would be happy if you create a pr for this feature. I would be more happy if you also add some tests and extend the readme file with this feature. I will encrease the version number, write the changelog and generate the package. 

Thanks in advance

**Comment by mtyski** [comment]
Hi @altmann, thanks for a quick reply! The pull request, including overloads implementation, unit tests and a short section in the README is opened and ready for review.

**Comment by altmann** [comment]
thank you for the great pr. I merged it already into the master branch. New package will be generated hopefully tomorrow.

**Comment by altmann** [comment]
New package is out: https://www.nuget.org/packages/FluentResults
