### ISSUE TITLE
Extension for merging

### ISSUE THREAD

**Issue by septst** [altmann/FluentResults#147]
Hello,

First off, I have been using FluentResults for a while and found it really great so far. I mostly use this library for Return Types like ```Result<some-type>```. I have a question or suggestion. I would like to collate multiple errors/reasons into one result and I use ```Result.Merge(...)``` for this purpose. I wonder if there is any better approach or any suggestion.

What I am currently doing
```
public static Result Validate(Person model)
{
    var result = Result.Ok();
    
   if (string.IsNullOrWhiteSpace(model.FirstName))
   {
            result = Result.Merge(
                result,
                Result.Fail($"{nameof(model.FirstName)} must not be empty"));
    }

   if (string.IsNullOrWhiteSpace(model.LastName))
   {
            result = Result.Merge(
                result,
                Result.Fail($"{nameof(model.LastName)} must not be empty"));
    }
   
    return result;
}
```

Can we consider having some extension like ```result.Merge(Result.Fail($"{nameof(model.LastName)} must not be empty"))```?  

Thank you!

**Comment by altmann** [comment]
Hi, thanks for your feedback. 

I'am dealing with the same scenario. I would write ... 

```csharp
public static Result Validate(Person model)
{
    return Result.Merge(
            Result.FailIf(string.IsNullOrWhiteSpace(model.FirstName), $"{nameof(model.FirstName)} must not be empty"),
            Result.FailIf(string.IsNullOrWhiteSpace(model.LastName)), $"{nameof(model.LastName)} must not be empty")
            );
}
```

If you still need a result.Merge(...) method then feel free to submit a pull request. The setup of FluentResults is very easy.

**Comment by septst** [comment]
Many thanks for your response. This is much more elegant than what I achieved with ```WithError``` as below

```public static Result Validate(Person model)
{
    var result = Result.Ok();
    
   if (string.IsNullOrWhiteSpace(model.FirstName))
   {
            result.WithError($"{nameof(model.FirstName)} must not be empty");
    }

   if (string.IsNullOrWhiteSpace(model.LastName))
   {
            result.WithError($"{nameof(model.LastName)} must not be empty");
    }
   
    return result;
}```

I have observed the following:
1. Using ```WithError``` changes the Result to Fail but not ```WithReason```. That made me rethink how to use reasons and errors.
2. The constructor of Result is public. Is this intentional? 

I will have a look into submitting a PR for merge extensions.

**Comment by altmann** [comment]
1. I don't really understand that. WithReason() has the same logic as WithError()
<img width="269" alt="image" src="https://user-images.githubusercontent.com/3706830/189528246-27d2770c-1cd5-4deb-9553-1b15f1a9480a.png">

2. Yes this is intentional. I think it was because to support a generic approach for that mediatr validation pipeline https://github.com/altmann/FluentResults/blob/master/src/FluentResults.Samples.MediatR/MediatRLogic/PipelineBehaviors/ValidationPipelineBehavior.cs
