### ISSUE TITLE
In LogIfFailed() the default logging level should be Error

### ISSUE THREAD

**Issue by schoetbi** [altmann/FluentResults#151]
When a result has Errors the default logging level in the various `LogIfFailed `methods should be `LogLevel.Error`. In case I want to have a warning instead, I could overwrite this. The current default value could lead to an error that will not be logged due to a mild logging level.

```
 public TResult LogIfFailed(string context, string content = null, LogLevel logLevel = LogLevel.Error)
        {
            if (IsFailed)
                return Log(context, content, logLevel);

            return (TResult)this;
        }
```

**Comment by altmann** [comment]
Hi, thank you. I will have a look at it.

**Comment by altmann** [comment]
The new package is out [3.14.0](https://www.nuget.org/packages/FluentResults/3.14.0)

Thank you for your feedback!
