### ISSUE TITLE
Add implicit conversion from string to Result.Fail(message)

### ISSUE THREAD

**Issue by schoetbi** [altmann/FluentResults#152]
In this method I want to return `Result<int>`. In case of an error I want to return the error message:

```cs
Result<int> GetValue(string key)
{
  var db=GetDbConnection();
  if (db == null)
  {
    return Result.Fail("Unable to connect to Database");
  }
  int value = db.GetValue(key);
  return value;
}
```

It would be nice to have an implict conversion from string to Result like this:

```cs
Result<int> GetValue(string key)
{
  var db=GetDbConnection();
  if (db == null)
  {
    return "Unable to connect to Database";
  }
  int value = db.GetValue(key);
  return value;
}
```

**Comment by altmann** [comment]
Hi, thanks for your feedback. 
I understand your issue. In FluentResult there is already an implicit conversion implemented - T can implicitly casted to Result<T>. 

``` csharp
Result<int> myResult1 = 23;
// myResult1.Value == 23 => true

Result<string> myResult2 = "my String Value";
// myResult2.Value == "my String Value" => true
```

Therefore it is not possible to add another implicit conversion. It would be too complicated and too hard to understand for the developers if we change it.

**Comment by schoetbi** [comment]
I understand especially if `Result<string>` is used. I close this issue. Thanks for looking into it.
