### ISSUE TITLE
How do I fill errors

### ISSUE THREAD

**Issue by michaelakin** [altmann/FluentResults#158]
I have tried a few things and don't see any difference for RootCause and I wonder how to fill in the errors instead of Reasons.

Here is my code: 

```
                catch (Exception ex)
                {
                    var error = new Error(ex.Message);
                    return Results.BadRequest(Result.Fail(new Error(ex.Message).CausedBy(ex)));
                }
```

And here is what I got as a result:

```
{
  "isFailed": true,
  "isSuccess": false,
  "reasons": [
    {
      "message": "Invalid code provided, please request a code again.",
      "metadata": {}
    }
  ],
  "errors": [
    {
      "reasons": [
        {
          "reasons": []
        }
      ]
    }
  ],
  "successes": []
}
```

I am sure I missed something in the documentation.  

Also, how have people converted the results of FluentValidation into your model so we only return 1 type of object back  instead of several different kinds of error models.

**Comment by michaelakin** [comment]
Since we should not serialize the object, I think you are saying to not use this as the return object for WebApi calls.  Am I understanding this correctly?

**Comment by altmann** [comment]
yes thats correct. Iam currently create a new package exactly for that scenario - details see #149 
I think I will release a preview version of it in the next weeks.

**Comment by michaelakin** [comment]
Thanks, I will look for it, but I have to create something now I think.
