### ISSUE TITLE
[Enhancement] Add Implicit conversion from Error to FailResult

### ISSUE THREAD

**Issue by RHaughton** [altmann/FluentResults#159]
Just like the Implicit Conversion to Ok Result.

just return;
`return new Error("msg");`

instead of :
`return Result.Fail(new Error("msg");`

**Comment by RHaughton** [comment]
just added a pull request : https://github.com/altmann/FluentResults/pull/160

**Comment by altmann** [comment]
Thanks for your feedback. I think its a good idea. I reviewed your pr and left some comments.

**Comment by altmann** [comment]
Released with https://www.nuget.org/packages/FluentResults/3.15.0
