### ISSUE TITLE
Result<object> results get packed twice

### ISSUE THREAD

**Issue by RchrdMgwtz** [altmann/FluentResults#165]
I have just come across a behaviour of the library that seems a little bit strange to me:

```csharp
class Program
{
    public static void Main()
    {
        Console.WriteLine(TestMethod().Value);
    }

    private static Result<object> TestMethod()
    {
        return Result.Ok(42);
    }
}
```
With this code snippet, I expected the value 42 to be output on the console. However, `TestMethod` returns a `Result`, which contains another `Result` as `Value`, containinig the 42. So the 42 is packed twice.

If, on the other hand, I cast the 42 directly to an `object`, the 42 is output on the console as expected.

```csharp
return Result.Ok((object)42);
```

What do you think about this?

**Comment by altmann** [comment]
Not good. I think its caused by an implicit cast operator. Would be great if you can debug it to find the root cause. If not then I will do it in the next days/weeks.

**Comment by RchrdMgwtz** [comment]
As far as I can see, the cause lies in the implicit cast in Result.cs:

```csharp
public static implicit operator Result<TValue>(TValue value)
{
    if (value is Result<TValue> r)
        return r;

    return Result.Ok(value);
}
```
Since `TValue` is `object` and `value` is of type `Result<int>`, the penultimate line wraps the value once again with a `Result.Ok()`.

**Comment by altmann** [comment]
@RchrdMgwtz Do you know a solution how we can fix it?

**Comment by altmann** [comment]
@agayev169 Thank you for the pr - I merged it today into the master.
