### ISSUE TITLE
[FluentResults.Extensions.FluentAssertions] .HaveValue(null) throws an exception then Type is a class

### ISSUE THREAD

**Issue by igorquintaes** [altmann/FluentResults#172]
When trying to assert if a Result contains a null return value, it throws a `System.NullReferenceException` when the the value type is a class. It still works with primitives/structs types.

It happens [here](https://github.com/altmann/FluentResults/blob/911699df5a5064f32a0f2c8e343473db79cdf9c8/src/FluentResults.Extensions.FluentAssertions/Assertions/AssertionOperators.cs#L101), because a null struct can call `.Equals()` while a class can't.

[primitive]: It works
```cs
public Result<int?> MethodExample() 
    => Result.Ok<int?>(null);

[Fact]
public void TestExample()
    => MethodExample().Should().BeSuccess().And.HaveValue(null);
```

[struct]: It works
```cs
public struct SomeStruct
{ }

public Result<SomeStruct?> MethodExample() 
    => Result.Ok<SomeStruct?>(null);

[Fact]
public void TestExample()
    => MethodExample().Should().BeSuccess().And.HaveValue(null);
```

[class]: It throws an exception

```cs
public class SomeClass
{ }

public Result<SomeClass?> MethodExample() 
    => Result.Ok<SomeClass?>(null);

[Fact]
public void TestExample()
    => MethodExample().Should().BeSuccess().And.HaveValue(null);  // <----- Exception here!
```

**Comment by altmann** [comment]
Thank you very much for the effort to improve this lib. It will be released in the next version.
