### ISSUE TITLE
Using Fluentresult Without MediatR & CQRS

### ISSUE THREAD

**Issue by Mahdihp** [altmann/FluentResults#191]
Using Fluentresult Without MediatR & CQRS...
How to use Fluentresult in Only FluentValidation ?

**Comment by Tvde1** [comment]
Just use it...

**Comment by altmann** [comment]
Thanks for your questions. @Tvde1 already answered it - FluentResult is standalone, the project samples with mediatr or cqrs are only samples to show FluentResults in different contexts.
