### ISSUE TITLE
BenchmarkDotNet error: FluentResults is non-optimized

### ISSUE THREAD

**Issue by bagoette** [altmann/FluentResults#194]
I was trying to run some benchmarks on a method that was returning a `Result` and `BenchmarkDotNet` gives the following error:

![image](https://github.com/altmann/FluentResults/assets/22378341/456c5916-4b0a-4ba0-9413-2bdae3556a9b)

- Versions 
  - FluentResults 3.15.2 (but I've tried all versions back to 3.14.0)
    - I can't find this release version on GitHub 
  - BenchmarkDotNet 0.13.7

I don't benchmark very often so maybe this is expected when using a Nuget, however, I thought I'd bring it up in case the build is misconfigured.

I can run the benchmarks by disabling the optimization validator so this isn't a road block for me.

I have a reproducible project here: https://github.com/bagoette/fluent-results-repro

**Comment by saborrie** [comment]
probably related to #195

**Comment by WojciechNagorski** [comment]
@altmann Can we fix this problem? I don't see the build script in the repo, so I can't prepare a PR.

**Comment by altmann** [comment]
Implemented with [v3.16](https://www.nuget.org/packages/FluentResults/3.16.0)
