### ISSUE TITLE
Binaries in nuget package compiled in debug mode

### ISSUE THREAD

**Issue by caveman-dick** [altmann/FluentResults#195]
Hi

I've just run debugdiag to check the perf of our site and I've just noticed that this isn't compiled in release mode:

![image](https://github.com/altmann/FluentResults/assets/516600/e9b79e7a-cdd3-419c-a8d6-b4772f906570)

**Comment by altmann** [comment]
Thanks for your feedback. 

CLOSED - this issue is a duplicate of #194
