### ISSUE TITLE
Overloaded method for Fail to accept multiple errors

### ISSUE THREAD

**Issue by ursathi** [altmann/FluentResults#20]
First of all thank you for this wonderful library. It really save so much of time & effort

I am having a requirement like below. I have two nested methods. Both returning Result object

```
Result<bool> Method1()
{
      var m2Result = Method2();
      if (m2Result.IsSuccess)
      {
           //Do some other operations
           return Results.Ok(true);
      }
      else
      {
           return Results.Fail<bool>(m2Result.Errors);       //Here I need to pass the list of errors for tracking purpose. However, at present Fail accepts only one Error object
      }
}

Result<int> Method2()
{
}
```
This is the problem I am currently facing. Hope my understanding about this library is correct.  Or, can we achieve the same by someother means? If not, would it be possible to include this functionality?

Thanks in advance

Regards
Athi

**Comment by altmann** [comment]
Thanks for your feedback. Your scenario can be done with the existing public api of FluentResults. See code below. 

```
Result<bool> Method1()
{
    var m2Result = Method2();
    if (m2Result.IsSuccess)
    {
        //Do some other operations
        return Results.Ok(true);
    }
    else
    {
        return m2Result.ToResult<bool>();
    }
}

Result<int> Method2()
{
}
```

If you have further feedback please write me. Feedback is most welcome.

**Comment by ursathi** [comment]
Fantastic @altmann . Thanks for your response.
