### ISSUE TITLE
Documentation of some methods shows as `<inheritdoc></inheritdoc>`

### ISSUE THREAD

**Issue by omarjuul** [altmann/FluentResults#205]
For example `Result.Value`:
![image](https://github.com/altmann/FluentResults/assets/28759079/8257c937-cb75-433e-938b-e055f218758d)

I think somehow somewhere in the packaging process a few `<`s get escaped maybe?

Version: `3.15.2` (via NuGet)

**Comment by Asafima** [comment]
Hey @omarjuul ,
From your screenshot, it seems like your code editor is rider (or another jetBrains tool).
This seems to be an issue of rider, view attached - https://youtrack.jetbrains.com/issue/RSRP-478940

The ```<inheritdoc/>``` element allows a type or member to inherit documentation comments from a base class or interface.
View this image from the source code - seems like it is used properly.

![image](https://github.com/altmann/FluentResults/assets/100016552/b453ce78-4e79-4324-97e7-3223b81c92ce)

This screenshot is from my code editor, VSCode:
![image](https://github.com/altmann/FluentResults/assets/100016552/31522288-cb43-4efd-a1c7-a0113c343e74)

**Comment by omarjuul** [comment]
Okay, thanks for the response (and sorry for the "false positive").
