### ISSUE TITLE
[Suggestion] Downgrade Microsoft.Extensions.Logging.Abstractions version

### ISSUE THREAD

**Issue by ebejko** [altmann/FluentResults#208]
The commit 3c765219 bumped the MEL Abstractions version to 6.0.1. From what I saw this dependency is used only for the LogLevel enum, and in my opinion should use the earliest possible (non deprecated) version of the library. The 2.1.0 or 2.1.1 version should be fine.

The problem came up when trying to add a recent version of this awesome library in a legacy project that forces an older version of MEL Abstractions.

**Comment by altmann** [comment]
Implemented with [v3.16](https://www.nuget.org/packages/FluentResults/3.16.0)

**Comment by chalmersj** [comment]
I have a project with MEL 8.0.0 and I'm getting an exception when using FluentResults:
```
System.TypeInitializationException: The type initializer for 'FluentResults.Result' threw an exception.
 ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The parameter is incorrect. (0x80070057 (E_INVALIDARG))
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> System.ArgumentException: IntegrationLoadContext requested assembly Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 version 2.1.1.0, but shared version 8.0.0.0 was found. Major versions must match.
```
Does this mean I can't use FluentResults unless I downgrade my dependency on MEL?

**Comment by savornicesei** [comment]
You can try ```<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` in your .props or .csproj file
