### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KarloX2** [altmann/FluentResults#21]
Hello!
Can you please add license information to this project. Is it MIT?

Thanks!

**Comment by altmann** [comment]
Hi,

thanks for the hint. Yes, it is licensed under MIT. I will add the license file asap - probably within the next days. 

BR Michael

**Comment by altmann** [comment]
@KarloX2 I added now the MIT license to the repository but I won't make a new nuget package.

**Comment by KarloX2** [comment]
Thanks!
