### ISSUE TITLE
Problem with HasSuccess - Creating a success puts in Value, not Successes where HasSuccess<type> looks

### ISSUE THREAD

**Issue by jasonmcfarlanekoerber** [altmann/FluentResults#210]
I am working on adding Fluent Results to my api.  In implementing a CreatedSuccess  class which extends Success, I am creating a Result.Ok(new CreateSuccess("/v1/Contacts", contactResult))

But when returning result.ToActionResult, in CustomAspNetCoreResultEndpointProfile I am testing for the result has success CreatedSuccess as follows:

        public override ActionResult TransformOkValueResultToActionResult<T>(OkResultToActionResultTransformationContext<Result<T>> context)
        {
            var result = context.Result;

            if (result.HasSuccess<CreatedSuccess>(out var createdSuccess))
            {
                return new CreatedResult(createdSuccess.First().Uri, createdSuccess.First().Value);
            }

            return new OkObjectResult(context.Result.ValueOrDefault);
        }

But the result has IsSuccess set to true, but the Successes collection in result is empty.
The Value property contains the success.

But the HasSuccess looks into the Successes collection.

Should I be creating the CreateSuccess differently or is there a bug in HasSuccess or ToActionResult?

**Comment by altmann** [comment]
I think that you misinterpret the Successes list. The Successes list contains only Success messages (similar to error messages). If you want to store a list of success values then you have to create a Result<List<CreatedSuccess>> and then you have to access it via .Value property. I hope this helps. See the documentation for more info: [https://github.com/altmann/FluentResults?tab=readme-ov-file#processing-a-result](https://github.com/altmann/FluentResults?tab=readme-ov-file#processing-a-result)

**Comment by jasonmcfarlanekoerber** [comment]
Hello Michael, I was applying the way errors were handled to handle success.

When you call

Result.Fail(new BadRequestError(ModelState))

This calls

    public static Result Fail(IError error)
    {
        Result result = new Result();
        result.WithError(error);
        return result;
    }

Following WithError eventually leads to WithReason which adds the reason to the base reasons:

   public TResult WithReason(IReason reason)
   {
       base.Reasons.Add(reason);
       return (TResult)this;
   }

But when you call

Result.Ok(new CreatedSuccess("/v1/Contacts", contactResult))

This calls

    public static Result<TValue> Ok<TValue>(TValue value)
    {
        Result<TValue> result = new Result<TValue>();
        result.WithValue(value);
        return result;
    }

WithValue just sets the Value.

   public Result<TValue> WithValue(TValue value)
   {
       Value = value;
       return this;
   }

So when I am working in CustomAspNetCoreResultEndpointProfile and building TransformFailedResultToActionResult and TransformOkValueResultToActionResult

For TransformFailedResultToActionResult I am checking to see if the results has specific errors as shown in examples

            if (result.HasError<BadRequestError>(out var badRequestErrors))
            {
            }

Since there was no TransformOkValueResultToActionResult example, I was working to use the same pattern for success since the result object has a HasSuccess method

            if (result.HasSuccess<CreatedSuccess>(out var createdSuccess))
            {
            }


But HasSuccess chains to ResultHelper.HasSuccess which looks at the successes, not the Value property.

    public static bool HasSuccess<TSuccess>(List<ISuccess> successes, Func<TSuccess, bool> predicate, out IEnumerable<TSuccess> result) where TSuccess : ISuccess
    {
        List<TSuccess> list = successes.OfType<TSuccess>().Where(predicate).ToList();
        if (list.Any())
        {
            result = list;
            return true;
        }

        result = Array.Empty<TSuccess>();
        return false;
    }

Your doc link has section for Handling success (GitHub - altmann/FluentResults: A generalised Result object implementation for .NET/C#<https://github.com/altmann/FluentResults?tab=readme-ov-file#handling-successes> ) which references result.HasSuccess<MyCustomSuccess>() but since the success is loaded into Value not Successes, this has not worked for me.

Please advise.

Thanks,
Jason
