### ISSUE TITLE
result.HasSuccess<CreatedSuccess>(out var createdSuccess) returns false but Success was added

### ISSUE THREAD

**Issue by jasonmcfarlanekoerber** [altmann/FluentResults#211]
I created a CreatedSuccess which extends Success

I call Result.Ok((new CreatedSuccess("/v1/Contacts", contactResult))
just like I do when I have a failure (Result.Fail(new BadRequestError()))

But result.HasSuccess<CreatedSuccess>() is not returning true unlike result.HasError<BadRequestError>()

When you call

Result.Fail(new BadRequestError(ModelState))

This calls

    public static Result Fail(IError error)
    {
        Result result = new Result();
        result.WithError(error);
        return result;
    }

Following WithError eventually leads to WithReason which adds the reason to the base reasons:

   public TResult WithReason(IReason reason)
   {
       base.Reasons.Add(reason);
       return (TResult)this;
   }

So the error is loaded into the Reasons collection.

But when you call

Result.Ok(new CreatedSuccess("/v1/Contacts", contactResult))

This calls

    public static Result<TValue> Ok<TValue>(TValue value)
    {
        Result<TValue> result = new Result<TValue>();
        result.WithValue(value);
        return result;
    }

WithValue just sets the Value, the success is not loaded into the Reasons.

   public Result<TValue> WithValue(TValue value)
   {
       Value = value;
       return this;
   }

So when I try running HasSuccess:

    public bool HasSuccess<TSuccess>(out IEnumerable<TSuccess> result) where TSuccess : ISuccess
    {
        return HasSuccess((TSuccess success) => true, out result);
    }

    public bool HasSuccess<TSuccess>(Func<TSuccess, bool> predicate, out IEnumerable<TSuccess> result) where TSuccess : ISuccess
    {
        return ResultHelper.HasSuccess(Successes, predicate, out result);
    }

    public static bool HasSuccess<TSuccess>(List<ISuccess> successes, Func<TSuccess, bool> predicate, out IEnumerable<TSuccess> result) where TSuccess : ISuccess
    {
        List<TSuccess> list = successes.OfType<TSuccess>().Where(predicate).ToList();
        if (list.Any())
        {
            result = list;
            return true;
        }

        result = Array.Empty<TSuccess>();
        return false;
    }

It will not find any as it is looking in the Successes collection.

Your doc link has section for Handling success (GitHub - altmann/FluentResults: A generalised Result object implementation for .NET/C#<https://github.com/altmann/FluentResults?tab=readme-ov-file#handling-successes> ) which references result.HasSuccess<MyCustomSuccess>() but since the success is loaded into Value not Successes, this has not worked for me.

I was following the Domain example for Fail and extrapolating to Ok to handle status code 201 versus 200.

Please advise.

Thanks,
Jason

**Comment by Kysluss** [comment]
Hi @jasonmcfarlanekoerber 

I think what you're seeing is expected because `Result.Ok` is meant to map whatever you pass into it as the `Value` property.  If you wanted to add something so that it's a success, you would have to do `Result.Ok().WithSuccess(mySuccess)`.  It doesn't look like there is an override of `Result.Ok` that takes a `Success` object.  This sort of makes sense because it would be difficult to know whether you meant to put that object on the `Value` prop or on in the collection of `Successes`.

Hopefully this helps and I understood your question correctly.

**Comment by jasonmcfarlanekoerber** [comment]
That makes sense.  Thanks



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
