### ISSUE TITLE
Nested Results returned by Result.Try

### ISSUE THREAD

**Issue by dguisinger** [altmann/FluentResults#222]
Maybe I'm not using it right, but I am trying to return my own Result within a Result.Try block and its returning Result<Result<T>> instead of Result<T>.

This means that my final result object returned by Result.Try is:

result  (try success/failed by exception)
result.value. (tried operation success/fail)
result.value.value (the actual return value)

This doesn't seem like proper behavior, in theory I should only want a single level of result, with fail being set either by an exception within the Try operation, or by any return Result.Fail(error)

While merge exists, I don't believe its correct to perform:
Result.Merge({ result,result.Value })
as I only want the root object's error from the possible exception, or the inner value's error or actual returned value....

Right now I'm doing the following, which feels ugly:
if (result.IsFailed) return result.ToResult();
return result.Value;

**Comment by Kysluss** [comment]
Hi @dguisinger, 

Are you doing this so that you can return a `Result.Fail` or are you just returning `Result.Ok`?  If only returning `Result.Ok`, you should be able to get around it by just returning the actual value instead wrapping it in the `Ok` method.  Hopefully that helps?

```csharp
// This
Result.Try(() => 5);

// Instead of
Result.Try(() => Result.Ok(5));
```

**Comment by dguisinger** [comment]
@Kysluss

In pseudo code, what I'm doing is

var result = Result.Try(() =>
{
      var item = GetItemFromDatabase();  // This could throw an exception if there is a database connection/query issue
      if (item==null) return Result.Fail(new NotFoundError());
      return Ok(item);
}
if (result.IsFailed) return result.ToResult();
return result.Value;

If I do as you suggest, I can't do the middle line to return an error condition.

**Comment by Kysluss** [comment]
@dguisinger

I see.  In a recent project of mine, I got around this by using `Try` + `Bind` together.  You would put your `GetItemFromDatabase` as the only thing in the `Try` method and then use `Bind` to decide what actual result type to return.

```csharp
var result = Result.Try(DoSomethingThatMayThrow)
    .Bind(i =>
    {
        if (i == 0) return Result.Fail("Why did you give me 0?");

        return Result.Ok();
    });

Console.WriteLine(result);

static int DoSomethingThatMayThrow() => 1;
```

**Comment by dguisinger** [comment]
@Kysluss  Thanks, finally got around to looking at this.  That worked.
