### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by milivojm** [altmann/FluentResults#32]
Hi, 

first, thank you for your great work. We're using your library and we'd like to know what is the best way to handle Error? 

For example at one point we return a failure:

`return Results.Fail(new MoResourceNotFoundError(entityIdentifier.Id));`

Now, handling (catching) it is a bit "unfriendly":

`if (moSetupResponse.Errors.Any(x => x is MoResourceNotFoundError)`

Maybe I'm missing some helper function?

Alternative is throwing/catching exceptions, but we'd like to avoid that here.

**Comment by altmann** [comment]
Hi,
Thanks! Glad you found the library helpful. 

Good point! Now there is no helper method but I think I can extend the public API of this library to support your team in this scenario. I will add ```HasError(...)``` and ```HasSuccess(...)``` methods. If you have any feedback, please reply. 

``` c#
var result = Results.Fail(new NotFoundError(3))
    .WithSuccess(new FoundSuccess(1));

result.IsFailed.Should().BeTrue();

// old way
result.Errors.Any(error => error is NotFoundError).Should().BeTrue();

// new way for errors
result.HasError<NotFoundError>().Should().BeTrue();
result.HasError<NotFoundError>(notFoundError => notFoundError.Id == 3).Should().BeTrue();

// new way for successes
result.HasSuccess<FoundSuccess>().Should().BeTrue();
result.HasSuccess<FoundSuccess>(foundSuccess => foundSuccess.Id == 1).Should().BeTrue();
```

Thanks for your feedback. If you think that some more functionality is missing please create an issue.

**Comment by altmann** [comment]
Today I extend the public api to support this scenario. 

New nuget package: https://www.nuget.org/packages/FluentResults/1.5.0
Section in readme: https://github.com/altmann/FluentResults#handlingcatching-errors

Please give feedback or close the issue. Thx

**Comment by milivojm** [comment]
Thank you for quick upgrade of your library!
