### ISSUE TITLE
Suggestion: Move ILogger to other namespace or rename

### ISSUE THREAD

**Issue by EnergyNick** [altmann/FluentResults#41]
Unfortunately when working with Asp.Net and Microsoft.Extensions.Logging constantly need set "using ILogger = Microsoft.Extensions.Logging.ILogger" because there is a match by name.

Would you consider this suggestion and rename or move ILogger?

**Comment by altmann** [comment]
Thanks for your feedback. 

Yes, I will rename the interface to IFluentResultLogger and publish a new version in the next days. 

If you have any other feedback, please let me know.

**Comment by EnergyNick** [comment]
Wonderful!
Thank you very much for your quick feedback and resolution of this issue 😄 👍

**Comment by altmann** [comment]
It's done. ILogger is renamed to IResultLogger. The new nuget package is already published: https://www.nuget.org/packages/FluentResults/1.6.0
