### ISSUE TITLE
JsonSerialize Exception because Result.Value is a throw 

### ISSUE THREAD

**Issue by ThiagoGodinhoPaschoalin** [altmann/FluentResults#55]
Hi, congratulations with lib, it's great. But a have a problem when try serialize my Result object.

My Scene:
![Anotação 2020-07-23 143619](https://user-images.githubusercontent.com/22103116/88319007-f05c8000-ccf1-11ea-929a-a44506105d0c.png)

I hope my exit is successful!

But, because "public bool IsFailed => Reasons.OfType<Error>().Any();", my 'Result.Value' is a throw, and Exception when a try serialize...

**Comment by altmann** [comment]
Thanks for your feedback. 

My opinion to use third party classes at system boundaries:
I highly recommend that the Result class from FluentResults is only used internally in your application. This means that a custom result class as data transfer object is used at the system boundaries. With an custom Result class you can make the custom Result class and the api stable and your api is independend from fluentresults breaking changes. The logic to transform a fluentresults Result object to a custom Result object for your api should bei easy. 
Then the dto is serialized and not the fluentresults object. Newtonsoft.Json or other serializer libs serialize all public properties. A fluentresults Result object has IsSuccess, IsFailed, Reasons, Successes, Errors properties and you definitly don't want that all properties are serialized (doublicate Data, ...). 

Throwing an exception when you access Value and the result is a failed result is a safety net and works as designed. If the result contains an error then its an failed result and you should not call .Value. With the exception the developer see asap the wrong usage of the result pattern. 

In your example you add in the last line an error with which you change the success result to a failed result. This behavoir is for me correct. 

Is this helpful?

**Comment by ThiagoGodinhoPaschoalin** [comment]
Perfect Michael, thank you.

I had a vision that 'Result.Ok()' was the success identifier, and the add-on.' WithFail()' not having the power of modification.
But with your explanation I understand that it takes a specific fit for my business.

Thank you so much for the explanation.
