### ISSUE TITLE
Port FluentResults to TypeScript

### ISSUE THREAD

**Issue by altmann** [altmann/FluentResults#56]
@JasonLandbridge wrote originally [here](https://github.com/altmann/FluentResults/issues/54#issuecomment-667818245)

> Also, I'm probably the biggest fan of FluentResults ever because I'm making a Typescript version of FluentResults as we speak, with the same syntax so it should work 1 on 1. It's called [FluentTypeResults](https://github.com/JasonLandbridge/FluentTypeResults) and I have just finished converting everything to Typescript, and now I will test it out in my own project.
> 
> The idea behind is to have my .NET Core WebApi always return a Fluent Result. And then in my Vue.js/Typescript front-end cast the API response to a Typescript Result and from there check if there are any errors which I would like to show to the user :D
> 
> Let me know is this is good or bad practice because I couldn't find any articles or resources on this.

**Comment by altmann** [comment]
First thanks @JasonLandbridge for your good feedback. 

**About using FluentResult types as Returntype of WebApis:**
I highly recommend that the Result class from FluentResults is only used internally in your application. This means that a custom result class as data transfer object is used at the system boundaries. With an custom Result class you can make the custom Result class and the api stable and your api is independend from fluentresults breaking changes. The logic to transform a fluentresults Result object to a custom Result object for your api should bei easy.
Then the dto is serialized and not the fluentresults object. Newtonsoft.Json or other serializer libs serialize all public properties. A fluentresults Result object has IsSuccess, IsFailed, Reasons, Successes, Errors properties and you definitly don't want that all properties are serialized (doublicate Data, computed properties are serialized, ...). This issue is also answered in #55. In another Result lib it is also already [answered ](https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/41)

- Why do you don't get the exception from #55? 
- Do you override the default json serialization configuration for Newtonsoft.Json/System.Text.Json?
- I looked at the readme of FluentTypeResults. How this example work? Can you explain it to me? Are you sure that the returned object is really a type from your FluentTypeResult lib and not only a dto. If its a typescript cast then its only a cast at design-time to make the typescript-"compiler" happy and not a cast at runtime. I'am curious how this works... 

**About FluentTypeResult**
For me its awesome that you @JasonLandbridge like the Result pattern and that you think that this pattern is also useful in typescript. It's great that also the js community can benefit from the Result pattern. 

Because I maintain FluentResults several years until now I take care of big changes like this. Therefore the following points are important for me:

- I evaluated the result pattern in multiple enterprise projects in almost 2 years before I push FluentResults into the public. My advice would be that you use FluentTypeResults in your projects and collect experience before you publish it into the wild. 

- Be aware that other projects/packages will depend on FluentTypeResults. So it is your responsibility to maintain the projects the next years. We will see how the community feedback is. 

- FluentResults should still be found easily over google. The name FluentTypeResults should be fine because with "Type" in the middle of the name causes no risk of confusion. 

- I would prefer that FluentResults and FluentTypeResults keep decoupled because I don't want to loose flexibility (release planning, compatibility, breaking changes, etc.). You can reuse the concepts and the public interface from FluentResults but I don't think that it makes sense that the api is a 1-1 match. I would prefer that you write in your readme "**... inspired by FluentResults**" and not "... is the Typescript version of FluentResults" to make the expectations clear. 

- In your readme "... works great together." In all my projects it was useful to decouple frontend and backend. I did that with a data transfer object which I already described above. So for sure in some projects it is useful to have also on the client a Result pattern library but it should be decoupled. For example I as a FluentResult and FluentTypeResult consumer I want to update FluentResult in the backend independendly from the use of FluentTypeResult. The dto and the transformation logic between FluentResult types to dto and the transformation logic between dto and FluentTypeResult enables flexibility and low coupling. 

Puh - long post. These are my thoughts NOW. I hope my points are clear. If not please let me know. Now its your turn, what do you think?

**Comment by JasonLandbridge** [comment]
Thank you very much for your extensive answer!

> **About using FluentResult types as Returntype of WebApis:**
> I highly recommend that the Result class from FluentResults is only used internally in your application. This means that a custom result class as data transfer object is used at the system boundaries. With an custom Result class you can make the custom Result class and the api stable and your api is independend from fluentresults breaking changes. The logic to transform a fluentresults Result object to a custom Result object for your api should bei easy.
> Then the dto is serialized and not the fluentresults object. Newtonsoft.Json or other serializer libs serialize all public properties. A fluentresults Result object has IsSuccess, IsFailed, Reasons, Successes, Errors properties and you definitly don't want that all properties are serialized (doublicate Data, computed properties are serialized, ...). This issue is also answered in #55. In another Result lib it is also already answered

I fully agree with this, I have in the meantime created my ResultDTO. Also because the value contained in the Result was outputted twice, in Value and in ValueOrDefault, which is inefficient when I already have big JSON's. 

Something simple like this:

```csharp
    public class ResultDTO
    {
        [JsonProperty("isFailed")]
        public bool IsFailed { get; set; }

        [JsonProperty("isSuccess")]
        public bool IsSuccess { get; set; }

        [JsonProperty("reasons")]
        public IList<Reason> Reasons { get; set; } = new List<Reason>();

        [JsonProperty("errors")]
        public IList<Error> Errors { get; set; } = new List<Error>();

        [JsonProperty("successes")]
        public IList<Success> Successes { get; set; } = new List<Success>();
    }

    public class ResultDTO<T> : ResultDTO
    {
        [JsonProperty("value", Required = Required.Always)]
        public T Value { get; set; }
    }
```

I use AutoMapper to then map between the Result and ResultDTO which works but so far I haven't fully tested the usage of errors/reasons in a front-end notification type of way but I am receiving them in the front-end in the json response. 

> Why do you don't get the exception from #55?

I think because my return type for the Api endpoints is `Task<IActionResult>`

```csharp
        public async Task<IActionResult> Get()
        {
            var result = await _plexDownloadService.GetAllDownloadsAsync();
            if (result.IsFailed)
            {
                return InternalServerError(result);
            }
            var mapResult = _mapper.Map<List<DownloadTaskDTO>>(result.Value);
            return Ok(Result.Ok(mapResult));
        }
```

Then I wrote some base methods such as `Ok()`:

```csharp
        [NonAction]
        protected IActionResult Ok<T>(Result<T> result)
        {
            // Filter our the value type
            var resultDTO = _mapper.Map<ResultDTO<T>>(result);
            return new OkObjectResult(resultDTO);
        }
```

> Do you override the default json serialization configuration for Newtonsoft.Json/System.Text.Json?

I'm using Newtonsoft.Json but I'm not doing anything special as far as I know, if there is an interest for it I would be happy to make a FluentResult WebApi sample with swagger where it is shown how I do it. 

> I looked at the readme of FluentTypeResults. How this example work? Can you explain it to me? Are you sure that the returned object is really a type from your FluentTypeResult lib and not only a dto. If its a typescript cast then its only a cast at design-time to make the typescript-"compiler" happy and not a cast at runtime. I'am curious how this works...

The return type is indeed the ResultDTO mentioned above and I use [Rx.Js](https://www.learnrxjs.io/) with [Axios-Observable](https://www.npmjs.com/package/axios-observable). 

Basically, my webapi responses are always of type ResultDTO or ResultDTO<T>, based on the success. This is then automatically parsed to the FluentTypeResult Result, and from there I can show the errors to the users. So far I haven't found a use for it outside of functioning as a Typescript DTO or as a "message carrier". I'm not using it as I would use it in the back-end as I view the front-end as purely a visual representation of back-end data and not for crunching data which might give errors.

> **About FluentTypeResult**
For me its awesome that you @JasonLandbridge like the Result pattern and that you think that this pattern is also useful in typescript. It's great that also the js community can benefit from the Result pattern.
> Because I maintain FluentResults several years until now I take care of big changes like this. Therefore the following points are important for me:

> - I evaluated the result pattern in multiple enterprise projects in almost 2 years before I push FluentResults into the public. My advice would be that you use FluentTypeResults in your projects and collect experience before you publish it into the wild.

Yes fully agree, I was thinking of posting FluentTypeResult to forums such as Reddit but I wanted to first test it out myself fully and make sure it is something that can be used in a big applications. So far I haven't mentioned this anywhere as I would like to first gather feedback and see for myself if it is useful and in which scenarios. 

> - Be aware that other projects/packages will depend on FluentTypeResults. So it is your responsibility to maintain the projects the next years. We will see how the community feedback is.

Yes agreed!

> - FluentResults should still be found easily over google. The name FluentTypeResults should be fine because with "Type" in the middle of the name causes no risk of confusion.

I'm open to any name changes but as you mentioned FluentTypeResults might suffice for now. 

> - I would prefer that FluentResults and FluentTypeResults keep decoupled because I don't want to loose flexibility (release planning, compatibility, breaking changes, etc.). You can reuse the concepts and the public interface from FluentResults but I don't think that it makes sense that the api is a 1-1 match. I would prefer that you write in your readme "... inspired by FluentResults" and not "... is the Typescript version of FluentResults" to make the expectations clear.

I kinda agree, so far the only purpose of FluentTypeResults is making a Typescript framework work with api responses that contain a Result object. This might in the future evolve to where errors in the front-end can be communicated to the back-end through the use of Results that are sent.  I would, respectfully, say that it makes sense to have it a 1-1 match since at this stage it's more of a "helper package", to deal with a niche use of Results being returned from the web API. This does mean that FluentResults should not care about a helper package and I'm also not sure if FluentTypeResult is even useful for anything other than what I described earlier or when used on its own without a FluentResult to go along with it. 

I will however change the Readme based on your suggestions.

> - In your readme "... works great together." In all my projects it was useful to decouple frontend and backend. I did that with a data transfer object which I already described above. So for sure in some projects it is useful to have also on the client a Result pattern library but it should be decoupled. For example I as a FluentResult and FluentTypeResult consumer I want to update FluentResult in the backend independendly from the use of FluentTypeResult. The dto and the transformation logic between FluentResult types to dto and the transformation logic between dto and FluentTypeResult enables flexibility and low coupling.

Yes fully agree, which is how I intend it to be. FluentTypeResult should be more of a helper package but I might have written the Readme slightly misleading and making it seem like a stand-alone package. All I did was translate the C# to Typescript, conserving the class structure and naming conventions since I find it well thought out but in conclusion, I'm honestly not sure what else I would like it to be. 

Maybe as my own project progresses I find more use for it in different ways but that remains to be seen. *cliffhanger*

**Comment by altmann** [comment]
> Thank you very much for your extensive answer!
> 
> > **About using FluentResult types as Returntype of WebApis:**
> > I highly recommend that the Result class from FluentResults is only used internally in your application. This means that a custom result class as data transfer object is used at the system boundaries. With an custom Result class you can make the custom Result class and the api stable and your api is independend from fluentresults breaking changes. The logic to transform a fluentresults Result object to a custom Result object for your api should bei easy.
> > Then the dto is serialized and not the fluentresults object. Newtonsoft.Json or other serializer libs serialize all public properties. A fluentresults Result object has IsSuccess, IsFailed, Reasons, Successes, Errors properties and you definitly don't want that all properties are serialized (doublicate Data, computed properties are serialized, ...). This issue is also answered in #55. In another Result lib it is also already answered
> 
> I fully agree with this, I have in the meantime created my ResultDTO. Also because the value contained in the Result was outputted twice, in Value and in ValueOrDefault, which is inefficient when I already have big JSON's.
> 
> Something simple like this:
> 
> ```cs
>     public class ResultDTO
>     {
>         [JsonProperty("isFailed")]
>         public bool IsFailed { get; set; }
> 
>         [JsonProperty("isSuccess")]
>         public bool IsSuccess { get; set; }
> 
>         [JsonProperty("reasons")]
>         public IList<Reason> Reasons { get; set; } = new List<Reason>();
> 
>         [JsonProperty("errors")]
>         public IList<Error> Errors { get; set; } = new List<Error>();
> 
>         [JsonProperty("successes")]
>         public IList<Success> Successes { get; set; } = new List<Success>();
>     }
> 
>     public class ResultDTO<T> : ResultDTO
>     {
>         [JsonProperty("value", Required = Required.Always)]
>         public T Value { get; set; }
>     }
> ```
> 
> I use AutoMapper to then map between the Result and ResultDTO which works but so far I haven't fully tested the usage of errors/reasons in a front-end notification type of way but I am receiving them in the front-end in the json response.

Great - this is what I mean. Decouple frontent and backend and don't transmit doublicate data. 👍 

> 
> > Why do you don't get the exception from #55?
> 
> I think because my return type for the Api endpoints is `Task<IActionResult>`
> 
> ```cs
>         public async Task<IActionResult> Get()
>         {
>             var result = await _plexDownloadService.GetAllDownloadsAsync();
>             if (result.IsFailed)
>             {
>                 return InternalServerError(result);
>             }
>             var mapResult = _mapper.Map<List<DownloadTaskDTO>>(result.Value);
>             return Ok(Result.Ok(mapResult));
>         }
> ```
> 
> Then I wrote some base methods such as `Ok()`:
> 
> ```cs
>         [NonAction]
>         protected IActionResult Ok<T>(Result<T> result)
>         {
>             // Filter our the value type
>             var resultDTO = _mapper.Map<ResultDTO<T>>(result);
>             return new OkObjectResult(resultDTO);
>         }
> ```
> 
> > Do you override the default json serialization configuration for Newtonsoft.Json/System.Text.Json?
> 
> I'm using Newtonsoft.Json but I'm not doing anything special as far as I know, if there is an interest for it I would be happy to make a FluentResult WebApi sample with swagger where it is shown how I do it.

Its fine for me. Thanks but I think its not necessary to create a sample project. 

> 
> > I looked at the readme of FluentTypeResults. How this example work? Can you explain it to me? Are you sure that the returned object is really a type from your FluentTypeResult lib and not only a dto. If its a typescript cast then its only a cast at design-time to make the typescript-"compiler" happy and not a cast at runtime. I'am curious how this works...
> 
> The return type is indeed the ResultDTO mentioned above and I use [Rx.Js](https://www.learnrxjs.io/) with [Axios-Observable](https://www.npmjs.com/package/axios-observable).
> 
> Basically, my webapi responses are always of type ResultDTO or ResultDTO, based on the success. This is then automatically parsed to the FluentTypeResult Result, and from there I can show the errors to the users. So far I haven't found a use for it outside of functioning as a Typescript DTO or as a "message carrier". I'm not using it as I would use it in the back-end as I view the front-end as purely a visual representation of back-end data and not for crunching data which might give errors.
> 
> > **About FluentTypeResult**
> > For me its awesome that you @JasonLandbridge like the Result pattern and that you think that this pattern is also useful in typescript. It's great that also the js community can benefit from the Result pattern.
> > Because I maintain FluentResults several years until now I take care of big changes like this. Therefore the following points are important for me:
> 
> > * I evaluated the result pattern in multiple enterprise projects in almost 2 years before I push FluentResults into the public. My advice would be that you use FluentTypeResults in your projects and collect experience before you publish it into the wild.
> 
> Yes fully agree, I was thinking of posting FluentTypeResult to forums such as Reddit but I wanted to first test it out myself fully and make sure it is something that can be used in a big applications. So far I haven't mentioned this anywhere as I would like to first gather feedback and see for myself if it is useful and in which scenarios.
> 
> > * Be aware that other projects/packages will depend on FluentTypeResults. So it is your responsibility to maintain the projects the next years. We will see how the community feedback is.
> 
> Yes agreed!
> 
> > * FluentResults should still be found easily over google. The name FluentTypeResults should be fine because with "Type" in the middle of the name causes no risk of confusion.
> 
> I'm open to any name changes but as you mentioned FluentTypeResults might suffice for now.
> 
> > * I would prefer that FluentResults and FluentTypeResults keep decoupled because I don't want to loose flexibility (release planning, compatibility, breaking changes, etc.). You can reuse the concepts and the public interface from FluentResults but I don't think that it makes sense that the api is a 1-1 match. I would prefer that you write in your readme "... inspired by FluentResults" and not "... is the Typescript version of FluentResults" to make the expectations clear.
> 
> I kinda agree, so far the only purpose of FluentTypeResults is making a Typescript framework work with api responses that contain a Result object. This might in the future evolve to where errors in the front-end can be communicated to the back-end through the use of Results that are sent. I would, respectfully, say that it makes sense to have it a 1-1 match since at this stage it's more of a "helper package", to deal with a niche use of Results being returned from the web API. This does mean that FluentResults should not care about a helper package and I'm also not sure if FluentTypeResult is even useful for anything other than what I described earlier or when used on its own without a FluentResult to go along with it.

For me its important, if its necessary to add a method in the public api (based on community feedback) I wanna add this new method and release a new package as fast as possible. I don't want to wait until the changes made in FluentTypeResults so that we have a 1:1 match. Both packages (FluentResults and FluentTypeResults) should be able to make a release independendly and asynchronous. This is for me flexibility. 
> 
> I will however change the Readme based on your suggestions.
> 
> > * In your readme "... works great together." In all my projects it was useful to decouple frontend and backend. I did that with a data transfer object which I already described above. So for sure in some projects it is useful to have also on the client a Result pattern library but it should be decoupled. For example I as a FluentResult and FluentTypeResult consumer I want to update FluentResult in the backend independendly from the use of FluentTypeResult. The dto and the transformation logic between FluentResult types to dto and the transformation logic between dto and FluentTypeResult enables flexibility and low coupling.
> 
> Yes fully agree, which is how I intend it to be. FluentTypeResult should be more of a helper package but I might have written the Readme slightly misleading and making it seem like a stand-alone package. All I did was translate the C# to Typescript, conserving the class structure and naming conventions since I find it well thought out but in conclusion, I'm honestly not sure what else I would like it to be.
> 
> Maybe as my own project progresses I find more use for it in different ways but that remains to be seen. _cliffhanger_

I keep this issue open for further discussions or feedback. If you need something from me please tell me.

**Comment by JasonLandbridge** [comment]
> For me its important, if its necessary to add a method in the public api (based on community feedback) I wanna add this new method and release a new package as fast as possible. I don't want to wait until the changes made in FluentTypeResults so that we have a 1:1 match. Both packages (FluentResults and FluentTypeResults) should be able to make a release independendly and asynchronous. This is for me flexibility.

No absolutely, that is my intention as well! Don't even consider the existence of FluentTypeResults :)

> I keep this issue open for further discussions or feedback. If you need something from me please tell me.

Thanks, I will let you know if and how it progresses!
