### ISSUE TITLE
How do we get back the exception added with CausedBy()?

### ISSUE THREAD

**Issue by Loreno10** [altmann/FluentResults#60]
When I finish all my operations and get the results, I want to display some logs. I wonder, how am I able to log information about the exception that is attached to a given `Error`? I see that the only property that I am able to access is `Message`.

**Comment by altmann** [comment]
The method ```CausedBy(..)``` adds an Error of type ```ExceptionalError``` to the Reasons list of the Error itself. 

Here is the internal code. 

``` csharp
public Error CausedBy(Exception exception)
{
     Reasons.Add(new ExceptionalError(exception));
     return this;
}
```

You can iterate it for example in this way

``` csharp
Result result = ....;
if (result.IsFailed)
   return;

foreach(var error in result.Errors)
{
    foreach(var causedByExceptionalError in error.Reasons.OfType<ExceptionalError>())
    {
        Console.WriteLine(causedByExceptionalError.Exception);
    }
}
```

I hope this helps. If not please let me know.

**Comment by altmann** [comment]
TODO: Improve docs in readme

**Comment by altmann** [comment]
readme improved. Issue closed
