### ISSUE TITLE
Great FluentAssertions Support

### ISSUE THREAD

**Issue by JasonLandbridge** [altmann/FluentResults#65]
Hi there, 

Is there a clean way to use the Result Errors in a [Fluent Assertions](https://fluentassertions.com/introduction) type of way. 

As an example:
`createResult.IsFailed.Should().BeFalse(createResult.Errors.ToString());`

This outputs something like:
```Expected createResult.IsFailed to be false because System.Collections.Generic.List`1[FluentResults.Error], but found True.```

My suggestion would be something like:
`createResult.IsFailed.Should().BeFalse(createResult.ErrorString);`

Which outputs something like:
```Expected createResult.IsFailed to be false because due to "'Height' must be greater than '0', 'Width' must be greater than '0'" and "'Size' must be greater than '0'", but found True.```

I understand the need to not create a dependency on the FluentAssertion package but otherwise an extension method would make it even more easy to use. 

Such as:
`createResult.ShouldBeValid();`

Which throws an exception outputting the errors.

Thanks in advance!

**Comment by altmann** [comment]
Thanks for the input. I already played a couple month ago with the assertion of results from FluentResults. I planned to publish it in october during hacktoberfest. Spoiler: The functionality to assert results will be a new nuget package and it will be work together with FluentAssertions. 

I use this issue for tracking so that you keep updated.

**Comment by JasonLandbridge** [comment]
Sounds great! Thank you!

**Comment by altmann** [comment]
@JasonLandbridge Today I played a little bit with the FluentAssertions support and this is until now my favorite solution:

https://github.com/altmann/FluentResults/blob/c4bafd98c74e03239ce6d963daa3d497810f9c47/src/FluentResults.Extensions.FluentAssertions/Class1.cs#L35

What do you think? Feedback is highly appreciated :)

**Comment by JasonLandbridge** [comment]
Yeah looks awesome! If it's stable, could you publish it? And then I will test it out in my own project!

**Comment by altmann** [comment]
@JasonLandbridge The new package FluentResults.Extensions.FluentAssertions is published. https://www.nuget.org/packages/FluentResults.Extensions.FluentAssertions/

You can use it - I appreciate your feedback! Docu/samples will be published in the next days.

**Comment by altmann** [comment]
And here is now the docu of the new package. https://github.com/altmann/FluentResults/wiki

**Comment by altmann** [comment]
I close this issue - the basic features are there. If someone needs more please create a new issue. Thanks @JasonLandbridge for creating this issue.
