### ISSUE TITLE
English Native Speaker wanted - review readme

### ISSUE THREAD

**Issue by altmann** [altmann/FluentResults#66]
Review the readme and correct to better english.

**Comment by deepank120896** [comment]
@altmann  I would like to pick this up

**Comment by altmann** [comment]
Great thanks. Please don't change the structure - only correct grammar etc.

**Comment by deepank120896** [comment]
A pull request has been opened for this: https://github.com/altmann/FluentResults/pull/69

**Comment by altmann** [comment]
Thank you very much @deepank120896 for your work. PR is already approved.
