### ISSUE TITLE
Wrapper function to catch exception and fill Results?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [altmann/FluentResults#72]
Would not it be nice to have a function that can wrap any execution and return `Result` instead with all the details nicely in an object rather than throwing an exception?

**Comment by altmann** [comment]
Hi, thanks for your feedback. Great idea! Can you post here an example how you want to use the function?

**Comment by Ibrahim-Islam** [comment]
At the top of my head, I was thinking of something like the following:

```csharp
public async Task<Result<Customer>> GetCustomerAsync(int id)
{
    //business code here...

    var customerResult = await GetResult(() => _repository.GetCustomerByIdAsync(id));

    //some more code here...

    return customerResult;
}
```

**Comment by altmann** [comment]
Thanks! I will have a look in the next days.

**Comment by Ibrahim-Islam** [comment]
If I can be of any assistance then please do let me know

**Comment by altmann** [comment]
@Ibrahim-Islam Do you mean something like that #74. Please have a look at the readme.

**Comment by Ibrahim-Islam** [comment]
@altmann Exactly! This is very cool 💯 / 💯

**Comment by altmann** [comment]
Thanks for your feedback. The new version will be published today or in the next days.

**Comment by altmann** [comment]
New version is published. https://www.nuget.org/packages/FluentResults/2.3.0
