### ISSUE TITLE
Additional OkIf and FailIf features

### ISSUE THREAD

**Issue by whortleberrybearer** [altmann/FluentResults#82]
Just started using the library to refactor some existing code I have.  I have a common scenario that has I have come across that I keep having to do something like:

```
public Result<Foo> GetTheFoos()
{
    Result<Bar> barsResult = GetTheBars();
 
    if (barsResult.IsFailed)
    {
        return barsResult.ToResult<Foo>();
    }
 
    return ConvertBarsToFoos(barsResult.Value);
}
```

Basically, I’m trying to come up with a way of shortcutting this, similar to the OkIf and FailIf methods, something like:

```
public Result<Foo> GetTheFoos()
{
    Result<Bar> barsResult = GetTheBars();
 
    return Result.FailIf<Foo>(barsResult, () => ConvertBarsToFoos(barsResult.Value));
}
```

Would these be suitable extensions to add?  Do have you any better ideas?

**Comment by whortleberrybearer** [comment]
Not sure how doable this is, or if it would just add confusion to anyone reading it.

```
public Result<Foo> GetTheFoos()
{
    Result.Something(() => GetTheBars(), bars => ConvertBarsToFoos(bars));
}
```

So, if `GetTheBars` fails, it returns that error, otherwise, the `Value` of `GetTheBars` is passed into the second function.

**Comment by altmann** [comment]
I don't want to loose you as consumer of my library but I think what you want is something like this: https://github.com/vkhorikov/CSharpFunctionalExtensions#wrap-multiple-operations-in-a-transactionscope This lib also implements the Result pattern but it also has these extension methods like Ensure, Tap, etc. With these methods you can implement your scenario in a way you want. Maybe you can copy the methods which you need to your project and make it work with FluentResults. Would be great if you can share your experience.

**Comment by whortleberrybearer** [comment]
I was looking at that library the other day, but it seemed too much for what I wanted to achieve,  I actually like the simplicity of this one in place of the basic result objects I normally end up with (with Value, Success and ErrorMessage properties).

I'll have a play at some point.  I wasn't overly sure the `FailIf` was the right way to go, it just fit in with your current API.  Borrowing the concept from the functional extensions `Ensure` may be a better name.

**Comment by altmann** [comment]
I'am a little bit afraid to add this logic in the library because I think it doesn't scale well. Another problem I see is readability. Different devs have different usecases and need different methods. I don't think that one method can provide the flexibility to support all these usecases. The solution would be to provide these extension methods from the other library and this is a lot of work. 

My suggestions: Maybe you can try to implement an appropriate solution for you in your code. I think it's not a must-have that this logic is within this library. You can add a ResultHelper or something with the method you want in your project. Gain experience in which scenarios you use this ResultHelper and then we can see further.

**Comment by whortleberrybearer** [comment]
Yes, I completely agree.  I also would try to avoid going down the route to the FluentExtensions library. There is a lot of functionality in there that has nothing to do with results and more to do with managing to lifecycle of an object passed through the chain.  The original suggestion only came about as I was mainly using functionality of the `Result` object.

My actual solution was a simple method.  However, I don’t think this really fits in well with your existing `Result` API.
```csharp
private static Result<T> EnsureSucceeded<T>(Result result, Func<Result<T>> nextAction)
{
    if (result.IsFailed)
    {
        return result.ToResult<T>();
    }
 
    return nextAction();
}
```

I did play around a bit more to come up with alternative.  The idea was to derive an `EnsureResult` from `Result` or `ResultBase` and add a `Then` method to it.  This is similar to the FluentAssertions library.  The use would be like so:

```csharp
{
    Result<Bar> barsResult = GetTheBars();

    return Result.EnsureSucceeded(barsResult).Then(() => ConvertBarsToFoos(barsResult.Value));
}
```

The `EnsureSucceeded` did very little except transforming the `result` parameter to an `EnsureResult`.  The `Then` method did something similar to the ` EnsureSucceeded` method above.

```csharp
public class EnsureResult<T> : ResultBase<EnsureResult<T>>
{
    public Result<T> Then(Func<Result<T>> nextAction)
    {
        if (this.IsFailed)
        {
            return new Result<T>().WithReasons(this.Reasons);
        }
 
        return nextAction();
    }
}
 
public static class MyResult
{
    public static EnsureResult<T> EnsureSucceeded<T>(Result<T> result)
    {
        return new EnsureResult<T>().WithReasons(result.Reasons);
    }
}
```

There would probably be nicer ways of transforming the `result` parameter if there were some constructors available that took parameters, but I was just working with what was there.

Anyway, I’m happy for you to close this if you don't want to include it.  Or if you do, I'll tidy it up and put a PR in.

**Comment by whortleberrybearer** [comment]
Going to close this as I agree it's not within the scope of the API.

However, if anyone ever finds this, the above examples could have been easily achieved by using the `Result<TNewValue> ToResult<TNewValue>(Func<TValue, TNewValue> valueConverter = null)` method.
