### ISSUE TITLE
[Enhancement] Add the ability to add a generic object (or non generic) to the Fail(reason) method

### ISSUE THREAD

**Issue by jeffward01** [altmann/FluentResults#88]
It would be nice to add an abstraction to the 'Fail' to where developers can add error codes and more details around the error.

See Facebook error codes for example:
https://developers.facebook.com/docs/graph-api/using-graph-api/error-handling

Personally, I use https://github.com/ardalis/SmartEnum **Smart Enums** for this usecase.

I would be able to pass this:

`Result.Fail(EnumIsInsertedHere, optionalStringMessage)`

Right now if I want to accomplish this I must create a new class inheriting from Result and modify the library.

I hope others will find this useful too.

The goal imo is to not throw exceptions, yet maintain a unified result model for methods. This allows us to work with API's and error messages easily.

Thanks!

**Comment by altmann** [comment]
Thank your for your issue. 

The FluentResults library is a very generic library. The goal is that the library can be used in every context - asp.net mvc application or a console application or in a class library. Therefore the library is designed in a way that the Error class can be customized for your specific needs. You can add further properties or set metadata. Details see [here](https://github.com/altmann/FluentResults#designing-errors-and-success-messages)

With the current implementation of FluentResults you can something like this:
```Result.Fail(new MyCustomError(SmartEnumObject))```

Maybe you can add an implicit cast from SmartEnum object to your custom Error class (SmartEnumObject to MyCustomError). Then you can write something like this:
```Result.Fail(SmartEnumObject); // here SmartEnumObject is casted to MyCustomError```
