### ISSUE TITLE
Extension methods for HttpResponsesCodes

### ISSUE THREAD

**Issue by FlippievanDyk** [altmann/FluentResults#91]
I am looking to use this library as a way to handle various different fail states that may occur in an Asp.Net API I am working on.

It's very rough at present, but essentially, I want to expose  extension methods like:
```C#
public static Result Forbid(this Result result, string message = "Forbidden!")
{
   return result.WithError(new HttpError<string>(HttpResponseCode.Forbidden, message));
 }
```

Would you be interested in this here, or not at all?

**Comment by altmann** [comment]
Hi. Thanks for your question. 

There was already a very similar question. See #1 
The goal of this lib kept the same all the years - FluentResults should be used in many different contexts and should be independent from infrastructure stuff. Http is such an infrastructure stuff. 

I think you can easily extend FluentResults in your project based on the existing extension points of FluentResults like in your example (create an HttpError class which inherit from base Error class).

If you want to share your http specific code with the world then you can create a separate nuget package. Again thanks for your question and that you use FluentResults. If you have more questions or you see some shortcomings in this lib please let me know.

**Comment by FlippievanDyk** [comment]
I didn't see #1 earlier, but yes, essentially the same.

I've only just started with this library, so I'll be sure to let you know if I find shortcomings. 

Thank you8 for all the hardwork you have put into this
